# Generated by Django 4.0.2 on 2022-05-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_book',
            name='paymentstatus',
            field=models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], default='U', max_length=11),
        ),
        migrations.AlterField(
            model_name='air_book',
            name='status',
            field=models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled'), ('D', 'Completed')], default='B', max_length=11),
        ),
        migrations.AlterField(
            model_name='bus_book',
            name='paymentstatus',
            field=models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], default='U', max_length=11),
        ),
        migrations.AlterField(
            model_name='bus_book',
            name='status',
            field=models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled'), ('D', 'Completed')], default='B', max_length=11),
        ),
        migrations.AlterField(
            model_name='launch_book',
            name='paymentstatus',
            field=models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], default='U', max_length=11),
        ),
        migrations.AlterField(
            model_name='launch_book',
            name='status',
            field=models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled'), ('D', 'Completed')], default='B', max_length=11),
        ),
        migrations.AlterField(
            model_name='train_book',
            name='paymentstatus',
            field=models.CharField(choices=[('P', 'Paid'), ('U', 'Unpaid')], default='U', max_length=11),
        ),
        migrations.AlterField(
            model_name='train_book',
            name='status',
            field=models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled'), ('D', 'Completed')], default='B', max_length=11),
        ),
    ]
