# Generated by Django 4.0.2 on 2022-05-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_air_book_paymentstatus_alter_air_book_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('transection', models.CharField(max_length=122)),
                ('vehicle', models.CharField(max_length=12)),
                ('pmethod', models.CharField(max_length=12)),
                ('datesent', models.DateField(null=True)),
            ],
        ),
    ]
