# Generated by Django 4.0.2 on 2022-05-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_book',
            name='paymentstatus',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=11),
        ),
        migrations.AlterField(
            model_name='air_book',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Booked', max_length=11),
        ),
        migrations.AlterField(
            model_name='bike',
            name='paymentstatus',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=11),
        ),
        migrations.AlterField(
            model_name='bike',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Requested', max_length=11),
        ),
        migrations.AlterField(
            model_name='bus_book',
            name='paymentstatus',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=11),
        ),
        migrations.AlterField(
            model_name='bus_book',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Booked', max_length=11),
        ),
        migrations.AlterField(
            model_name='car',
            name='paymentstatus',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=11),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Requested', max_length=11),
        ),
        migrations.AlterField(
            model_name='cng',
            name='paymentstatus',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=11),
        ),
        migrations.AlterField(
            model_name='cng',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Requested', max_length=11),
        ),
        migrations.AlterField(
            model_name='launch_book',
            name='paymentstatus',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=11),
        ),
        migrations.AlterField(
            model_name='launch_book',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Booked', max_length=11),
        ),
        migrations.AlterField(
            model_name='microbus',
            name='paymentstatus',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=11),
        ),
        migrations.AlterField(
            model_name='microbus',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Requested', max_length=11),
        ),
        migrations.AlterField(
            model_name='train_book',
            name='paymentstatus',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=11),
        ),
        migrations.AlterField(
            model_name='train_book',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Booked', max_length=11),
        ),
    ]
